/* global window,document,console,process */
import {chromium,devices} from 'playwright';import {mkdir,writeFile} from 'node:fs/promises';
const out='docs/asset-reports/game';await mkdir(out,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});const reports=[];
try{for(const mode of ['desktop','mobile']){const context=await browser.newContext(mode==='mobile'?devices['Pixel 7']:{viewport:{width:1440,height:1000}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('404'))errors.push(m.text());});await page.goto('http://127.0.0.1:4175/?audit=1');await page.waitForFunction(()=>window.__CHESS_DIAGNOSTICS__?.assetStats?.loading===0&&window.__CHESS_DIAGNOSTICS__?.assetStats?.failed===0&&window.__CHESS_DIAGNOSTICS__?.pieces?.length===32&&window.__CHESS_DIAGNOSTICS__?.pieces?.every(p=>p.status==='ready'),{}, {timeout:90000});
 for(const effect of ['full','reduced','off']){await page.getByLabel('打开设置').click();await page.getByRole('button',{name:effect==='full'?'完整':effect==='reduced'?'简洁':'关闭',exact:true}).click();await page.getByLabel('关闭设置').click();await page.waitForTimeout(3500);const m=await page.evaluate(()=>window.__CHESS_DIAGNOSTICS__);delete m.points;delete m.pieces;reports.push({mode,effect,...m,errors:[...errors]});await page.screenshot({path:`${out}/${mode}-${effect}.png`});console.log('PERF',mode,effect,m.p95,m.draws);}
 await page.getByLabel('切换顶视').click();await page.waitForTimeout(1500);await page.screenshot({path:`${out}/${mode}-top.png`});
 const layout=await page.evaluate(()=>{const d=window.__CHESS_DIAGNOSTICS__,c=document.querySelector('canvas').getBoundingClientRect();return {camera:d.camera,all90PointsVisible:d.points.length===90&&d.points.every(p=>p.x>4&&p.y>4&&p.x<c.width-4&&p.y<c.height-4),topRowSkew:Math.abs(d.points[0].y-d.points[8].y)};});
 reports.push({mode,topLayout:layout});if(!layout.all90PointsVisible||layout.topRowSkew>3)throw new Error(mode+' top camera clips or rotates the board');
 await page.getByLabel('打开设置').click();await page.getByRole('button',{name:'精细',exact:true}).waitFor();await page.screenshot({path:`${out}/${mode}-settings.png`});await page.getByLabel('关闭设置').click();
 const click=async(file,rank)=>{const p=await page.evaluate(([f,r])=>window.__CHESS_DIAGNOSTICS__.points.find(p=>p.file===f&&p.rank===r),[file,rank]);const box=await page.locator('canvas').boundingBox();await page.mouse.click(box.x+p.x,box.y+p.y);await page.waitForTimeout(150);};
 await click(4,6);await click(4,5);await page.getByText('兵五进1').waitFor();await page.waitForTimeout(180);await click(4,3);await click(4,4);await page.getByText('卒五进1').waitFor();await page.waitForTimeout(180);await click(4,5);await click(4,4);await page.waitForFunction(()=>window.__CHESS_DIAGNOSTICS__.pieces.length===31,{}, {timeout:5000});
 await page.screenshot({path:`${out}/${mode}-capture.png`});await page.getByLabel('悔棋').click();await page.waitForFunction(()=>window.__CHESS_DIAGNOSTICS__.pieces.length===32,{}, {timeout:5000});reports.push({mode,capture_and_undo:true,errors});await context.close();}
}finally{await browser.close();await writeFile(out+'/performance.json',JSON.stringify(reports,null,2));}
if(reports.some(r=>r.errors?.length))process.exitCode=1;
